#!/usr/bin/env python3
"""Decide whether the slow validation suite needs to run.

The SHACL suite and the regression tests take roughly three and a half minutes,
and most commits touch documentation or the generated site rather than the
vocabulary. This gate hashes the normative inputs -- the ontology modules, SHACL
profiles, per-version registries, examples, mappings, validation code, coverage
inputs and the declared version -- into a single digest recorded in
``tests/.validation-stamp.json``. When that digest is unchanged, the slow suite
is skipped.

Documentation is deliberately excluded, so editing prose never triggers a
three-minute wait. The fast checks always run and cover those files.

This stamp is a build cache, not a provenance record: it deliberately stores one
combined digest rather than a per-file hash table. Use ``git status`` to see which
files changed. The assessments keep their own provenance -- see
``coverage/methodology/generated/provenance.json`` and ``sources.lock.json``.

  --check   exit 0 if the stamp is current (skip), 3 if the suite must run
  --update  rewrite the stamp for the current inputs
  --status  report whether the suite must run, without changing anything
"""
from __future__ import annotations

import argparse
import hashlib
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
STAMP = ROOT / "tests" / ".validation-stamp.json"

# Globs whose content decides whether the slow suite must run.
PATTERNS = [
    "ontology/*.ttl",
    "ontology/versions/*",
    "shacl/*.ttl",
    "examples/**/*",
    "mappings/*",
    "tests/*.py",
    "tests/*.mjs",
    "coverage/vcf45-inventory/inventory.json",
    "coverage/vcf45-inventory/*.py",
    "tests/shacl/**/*",
    "scripts/*.py",
    "scripts/*.mjs",
    "coverage/methodology/scripts/*.py",
    "coverage/methodology/tests/*.py",
    "coverage/methodology/inputs/*.json",
    "coverage/methodology/fixtures/*.vcf",
    "coverage/methodology/queries/*.rq",
    "coverage/methodology/sources.lock.json",
    "coverage/methodology/requirements.txt",
    "coverage/methodology/sources/*.tex",
    "requirements-dev.txt",
    "package.json",
]
# Generated from the modules on every build; including it would always differ.
EXCLUDE = {"ontology/vcf-core-vocabulary.bundle.ttl"}


def inputs() -> list[pathlib.Path]:
    seen: set[pathlib.Path] = set()
    for pattern in PATTERNS:
        for path in ROOT.glob(pattern):
            rel = path.relative_to(ROOT).as_posix()
            if (path.is_file() and rel not in EXCLUDE and path.name != '.DS_Store'
                    and '__pycache__' not in path.parts):
                seen.add(path)
    return sorted(seen)


def fingerprint() -> tuple[str, int]:
    """One digest over every normative input's path and content."""
    per_file = {
        path.relative_to(ROOT).as_posix(): hashlib.sha256(path.read_bytes()).hexdigest()
        for path in inputs()
    }
    combined = hashlib.sha256(
        "\n".join(f"{name}:{digest}" for name, digest in sorted(per_file.items())).encode()
    ).hexdigest()
    return combined, len(per_file)


def declared_version() -> str:
    return json.loads((ROOT / "package.json").read_text()).get("version", "?")


def load_stamp() -> dict:
    if not STAMP.exists():
        return {}
    try:
        return json.loads(STAMP.read_text())
    except json.JSONDecodeError:
        return {}


def write_stamp(combined: str, count: int) -> None:
    STAMP.write_text(json.dumps({
        "$comment": "Build cache: one digest over the normative inputs at the last successful "
                    "full validation. Regenerated by scripts/validation-gate.py --update; "
                    "do not edit by hand. Not a provenance record -- see the coverage "
                    "assessments for those.",
        "version": declared_version(),
        "files": count,
        "digest": combined,
    }, indent=1) + "\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--check", action="store_true")
    group.add_argument("--update", action="store_true")
    group.add_argument("--status", action="store_true")
    args = parser.parse_args()

    combined, count = fingerprint()
    stamp = load_stamp()
    version = declared_version()
    current = bool(stamp) and stamp.get("digest") == combined and stamp.get("version") == version

    if args.update:
        write_stamp(combined, count)
        print(f"Validation stamp updated: version {version}, {count} normative files.")
        return 0

    if args.status or args.check:
        if not stamp:
            print("No validation stamp recorded; the full suite must run.")
            return 0 if args.status else 3
        if stamp.get("version") != version:
            print(f"Version changed ({stamp.get('version')} -> {version}); the full suite must run.")
            return 0 if args.status else 3
        if not current:
            print(f"Normative inputs changed since the last full validation "
                  f"({count} files now tracked); the full suite must run. "
                  f"Run 'git status' to see which files differ.")
            return 0 if args.status else 3
        print(f"Normative inputs unchanged since the last full validation "
              f"(version {version}, {count} files). Skipping the slow suite; "
              f"run 'npm run validate:force' to override.")
        return 0
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
