#!/usr/bin/env python3
"""Decide whether the slow validation suite needs to run.

The SHACL suite and the regression probes take roughly three and a half
minutes, and most commits touch the manuscript, the README or the generated
site rather than the vocabulary. This gate fingerprints the normative inputs
-- the ontology modules, SHACL profiles, per-version registries, examples,
mappings, validation code and the declared version -- and records the result in
``tests/.validation-stamp.json``. When nothing in that set has changed since
the stamp, the slow suite is skipped.

The manuscript and documentation are deliberately excluded, so editing prose
never triggers a three-minute wait. The fast checks (RDF parse, coverage report
and the paper-figure consistency check) always run and cover those files.

  --check   exit 0 if the stamp is current (skip), 3 if the suite must run
  --update  rewrite the stamp for the current inputs
  --status  print what changed, without changing anything
"""
from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
STAMP = ROOT / "tests" / ".validation-stamp.json"

# Globs whose content decides whether the slow suite must run.
PATTERNS = [
    "ontology/*.ttl",
    "ontology/versions/*",
    "shacl/*.ttl",
    "examples/**/*",
    "mappings/*",
    "tests/*.py",
    "tests/*.mjs",
    "coverage/curated/inventory.json",
    "coverage/curated/*.py",
    "coverage/paper/*.py",
    "coverage/paper/*.mjs",
    "coverage/paper/*.ttl",
    "coverage/paper/*.vcf",
    "coverage/paper/*.rq",
    "tests/shacl/**/*",
    "scripts/*.py",
    "scripts/*.mjs",
    "coverage/methodological/*.py",
    "coverage/methodological/*.json",
    "coverage/methodological/probes/*.json",
    "coverage/methodological/requirements.txt",
    "coverage/methodological/sources/*.tex",
    "requirements-dev.txt",
    "package.json",
]
# Generated from the modules on every build; including it would always differ.
EXCLUDE = {"ontology/vcf-core-vocabulary.bundle.ttl"}


def inputs() -> list[pathlib.Path]:
    seen: set[pathlib.Path] = set()
    for pattern in PATTERNS:
        for path in ROOT.glob(pattern):
            rel = path.relative_to(ROOT).as_posix()
            if (path.is_file() and rel not in EXCLUDE and path.name != '.DS_Store'
                    and '__pycache__' not in path.parts):
                seen.add(path)
    return sorted(seen)


def fingerprint() -> tuple[str, dict[str, str]]:
    per_file: dict[str, str] = {}
    for path in inputs():
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        per_file[path.relative_to(ROOT).as_posix()] = digest
    combined = hashlib.sha256(
        "\n".join(f"{name}:{digest}" for name, digest in sorted(per_file.items())).encode()
    ).hexdigest()
    return combined, per_file


def declared_version() -> str:
    return json.loads((ROOT / "package.json").read_text()).get("version", "?")


def load_stamp() -> dict:
    if not STAMP.exists():
        return {}
    try:
        return json.loads(STAMP.read_text())
    except json.JSONDecodeError:
        return {}


def write_stamp(combined: str, per_file: dict[str, str]) -> None:
    STAMP.write_text(json.dumps({
        "$comment": "Fingerprint of the normative inputs at the last successful full validation. "
                    "Regenerated by scripts/validation-gate.py --update; do not edit by hand.",
        "version": declared_version(),
        "files": len(per_file),
        "digest": combined,
        "perFile": dict(sorted(per_file.items())),
    }, indent=1) + "\n")


def changes(stamp: dict, per_file: dict[str, str]) -> list[str]:
    previous = stamp.get("perFile", {})
    out = [f"changed: {n}" for n in sorted(per_file) if n in previous and previous[n] != per_file[n]]
    out += [f"added:   {n}" for n in sorted(set(per_file) - set(previous))]
    out += [f"removed: {n}" for n in sorted(set(previous) - set(per_file))]
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--check", action="store_true")
    group.add_argument("--update", action="store_true")
    group.add_argument("--status", action="store_true")
    args = parser.parse_args()

    combined, per_file = fingerprint()
    stamp = load_stamp()
    version = declared_version()
    current = bool(stamp) and stamp.get("digest") == combined and stamp.get("version") == version

    if args.update:
        write_stamp(combined, per_file)
        print(f"Validation stamp updated: version {version}, {len(per_file)} normative files.")
        return 0

    if args.status or args.check:
        if not stamp:
            print("No validation stamp recorded; the full suite must run.")
            return 0 if args.status else 3
        if stamp.get("version") != version:
            print(f"Version changed ({stamp.get('version')} -> {version}); the full suite must run.")
            return 0 if args.status else 3
        if not current:
            diffs = changes(stamp, per_file)
            print(f"{len(diffs)} normative input(s) changed since the last full validation:")
            for line in diffs[:20]:
                print(f"  {line}")
            if len(diffs) > 20:
                print(f"  ... and {len(diffs) - 20} more")
            return 0 if args.status else 3
        print(f"Normative inputs unchanged since the last full validation "
              f"(version {version}, {len(per_file)} files). Skipping the slow suite; "
              f"run 'npm run validate:force' to override.")
        return 0
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
